### ISSUE TITLE
final touches

### ISSUE THREAD

**Issue by henry-hz** [henry-hz/wepy-wallet#3]
- change the splash to use our logo (also the wizard)
- change the icon logo to our logo
- setup default country to +55 (Brazil)
- fix the bug that even when using +972 or another country, it sends the SMS to +1 (USA) [pls see the log below]
- hide the points/fuse buttons

**Comment by henry-hz** [comment]
@LiorAgnin only pointing me to the right files, and I can do it.

**Comment by LiorAgnin** [comment]
@henry-hz  I will open a PR with all the changes you asked soon.

**Comment by henry-hz** [comment]
@LiorAgnin the visual is amazing, but found transaction error when creating the wallet.
```

I/flutter ( 6945): response: 200, OK
I/flutter ( 6945): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:118:22)
I/flutter ( 6945): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter ( 6945): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                                                                                                      
I/flutter ( 6945): │ 👾 [INFO] Job: JoinCommunityJob not done
I/flutter ( 6945): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): GET v2/jobs/5e5664c3d05c2800134616c1
I/flutter ( 6945): response: 200, OK
I/flutter ( 6945): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:118:22)
I/flutter ( 6945): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter ( 6945): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                                                                                                      
I/flutter ( 6945): │ 👾 [INFO] Job: JoinCommunityJob not done
I/flutter ( 6945): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): GET v2/jobs/5e5664c3d05c2800134616c1
I/flutter ( 6945): response: 200, OK
I/flutter ( 6945): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:118:22)
I/flutter ( 6945): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter ( 6945): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                                                                                                      
I/flutter ( 6945): │ 👾 [INFO] Job: JoinCommunityJob not done
I/flutter ( 6945): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): GET v2/jobs/5e5664c3d05c2800134616c1
I/flutter ( 6945): response: 200, OK
I/flutter ( 6945): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:118:22)
I/flutter ( 6945): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter ( 6945): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                                                                                                      
I/flutter ( 6945): │ 👾 [INFO] action: Track - Wallet: SUCCEEDED job 5e5664c3d05c2800134616c1 relay
I/flutter ( 6945): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): response: 200, OK
I/flutter ( 6945): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                                                                                      
I/flutter ( 6945): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:118:22)
I/flutter ( 6945): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter ( 6945): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                                                                                                      
I/flutter ( 6945): │ 👾 [INFO] Job: JoinBonusJob FAILED
I/flutter ( 6945): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────     

```
